USE EcommerceBusinessAnalysis;
GO

/* =========================================================
   SQL E-COMMERCE BUSINESS INSIGHTS ANALYSIS
   Tool: SQL Server / SSMS
   ========================================================= */


/* 1. CUSTOMER ORDERS
   Business Question:
   Which customers placed which orders, and when?
*/

SELECT 
    c.Customer_ID,
    c.Customer_Name,
    c.City,
    o.Order_ID,
    o.Order_Date
FROM Customers c
INNER JOIN Orders o
    ON c.Customer_ID = o.Customer_ID;


/* 2. CUSTOMER ORDER COUNT
   Business Question:
   Which customers placed the most orders?
*/

SELECT 
    c.Customer_Name,
    COUNT(o.Order_ID) AS Total_Orders
FROM Customers c
INNER JOIN Orders o
    ON c.Customer_ID = o.Customer_ID
GROUP BY c.Customer_Name
ORDER BY Total_Orders DESC;


/* 3. REVENUE BY ORDER ITEM
   Business Question:
   What revenue was generated from each ordered product?
*/

SELECT 
    o.Order_ID,
    p.Product_Name,
    od.Quantity,
    p.Price,
    od.Discount,
    (od.Quantity * p.Price * (1 - od.Discount)) AS Revenue
FROM Orders o
INNER JOIN Order_Details od
    ON o.Order_ID = od.Order_ID
INNER JOIN Products p
    ON od.Product_ID = p.Product_ID;


/* 4. TOTAL BUSINESS REVENUE
   Business Question:
   What is the total revenue generated by the business?
*/

SELECT 
    SUM(od.Quantity * p.Price * (1 - od.Discount)) AS Total_Revenue
FROM Order_Details od
INNER JOIN Products p
    ON od.Product_ID = p.Product_ID;


/* 5. CATEGORY-WISE REVENUE
   Business Question:
   Which product category generates the highest revenue?
*/

SELECT 
    p.Category,
    SUM(od.Quantity * p.Price * (1 - od.Discount)) AS Category_Revenue
FROM Order_Details od
INNER JOIN Products p
    ON od.Product_ID = p.Product_ID
GROUP BY p.Category
ORDER BY Category_Revenue DESC;


/* 6. REGION-WISE REVENUE
   Business Question:
   Which region generates the highest revenue?
*/

SELECT 
    o.Region,
    SUM(od.Quantity * p.Price * (1 - od.Discount)) AS Region_Revenue
FROM Orders o
INNER JOIN Order_Details od
    ON o.Order_ID = od.Order_ID
INNER JOIN Products p
    ON od.Product_ID = p.Product_ID
GROUP BY o.Region
ORDER BY Region_Revenue DESC;


/* 7. CUSTOMER-WISE REVENUE
   Business Question:
   Which customers generate the most revenue?
*/

SELECT 
    c.Customer_ID,
    c.Customer_Name,
    SUM(od.Quantity * p.Price * (1 - od.Discount)) AS Customer_Revenue
FROM Customers c
INNER JOIN Orders o
    ON c.Customer_ID = o.Customer_ID
INNER JOIN Order_Details od
    ON o.Order_ID = od.Order_ID
INNER JOIN Products p
    ON od.Product_ID = p.Product_ID
GROUP BY 
    c.Customer_ID,
    c.Customer_Name
ORDER BY Customer_Revenue DESC;


/* 8. TOP 5 CUSTOMERS BY REVENUE
   Business Question:
   Who are the top five revenue-generating customers?
*/

SELECT TOP 5
    c.Customer_ID,
    c.Customer_Name,
    SUM(od.Quantity * p.Price * (1 - od.Discount)) AS Customer_Revenue
FROM Customers c
INNER JOIN Orders o
    ON c.Customer_ID = o.Customer_ID
INNER JOIN Order_Details od
    ON o.Order_ID = od.Order_ID
INNER JOIN Products p
    ON od.Product_ID = p.Product_ID
GROUP BY 
    c.Customer_ID,
    c.Customer_Name
ORDER BY Customer_Revenue DESC;


/* 9. PRODUCTS PRICED ABOVE AVERAGE
   Business Question:
   Which products are priced above the average product price?
   Technique: Subquery
*/

SELECT 
    Product_ID,
    Product_Name,
    Category,
    Price
FROM Products
WHERE Price >
(
    SELECT AVG(Price)
    FROM Products
);


/* 10. CUSTOMERS WITH ABOVE-AVERAGE REVENUE
    Business Question:
    Which customers generate revenue above the average customer revenue?
    Technique: Subqueries
*/

SELECT 
    Customer_ID,
    Customer_Name,
    Customer_Revenue
FROM
(
    SELECT 
        c.Customer_ID,
        c.Customer_Name,
        SUM(od.Quantity * p.Price * (1 - od.Discount)) AS Customer_Revenue
    FROM Customers c
    INNER JOIN Orders o
        ON c.Customer_ID = o.Customer_ID
    INNER JOIN Order_Details od
        ON o.Order_ID = od.Order_ID
    INNER JOIN Products p
        ON od.Product_ID = p.Product_ID
    GROUP BY 
        c.Customer_ID,
        c.Customer_Name
) AS CustomerSales
WHERE Customer_Revenue >
(
    SELECT AVG(Customer_Revenue)
    FROM
    (
        SELECT 
            c.Customer_ID,
            SUM(od.Quantity * p.Price * (1 - od.Discount)) AS Customer_Revenue
        FROM Customers c
        INNER JOIN Orders o
            ON c.Customer_ID = o.Customer_ID
        INNER JOIN Order_Details od
            ON o.Order_ID = od.Order_ID
        INNER JOIN Products p
            ON od.Product_ID = p.Product_ID
        GROUP BY c.Customer_ID
    ) AS AvgCustomerSales
)
ORDER BY Customer_Revenue DESC;


/* 11. CUSTOMER REVENUE USING CTE
    Business Question:
    Display customer-wise revenue using a readable CTE structure.
*/

WITH CustomerRevenue AS
(
    SELECT
        c.Customer_ID,
        c.Customer_Name,
        SUM(od.Quantity * p.Price * (1 - od.Discount)) AS Total_Revenue
    FROM Customers c
    INNER JOIN Orders o
        ON c.Customer_ID = o.Customer_ID
    INNER JOIN Order_Details od
        ON o.Order_ID = od.Order_ID
    INNER JOIN Products p
        ON od.Product_ID = p.Product_ID
    GROUP BY
        c.Customer_ID,
        c.Customer_Name
)
SELECT *
FROM CustomerRevenue
ORDER BY Total_Revenue DESC;


/* 12. TOP 5 CUSTOMERS USING CTE
    Business Question:
    Identify the top five customers by total revenue using a CTE.
*/

WITH CustomerRevenue AS
(
    SELECT
        c.Customer_ID,
        c.Customer_Name,
        SUM(od.Quantity * p.Price * (1 - od.Discount)) AS Total_Revenue
    FROM Customers c
    INNER JOIN Orders o
        ON c.Customer_ID = o.Customer_ID
    INNER JOIN Order_Details od
        ON o.Order_ID = od.Order_ID
    INNER JOIN Products p
        ON od.Product_ID = p.Product_ID
    GROUP BY
        c.Customer_ID,
        c.Customer_Name
)
SELECT TOP 5
    Customer_ID,
    Customer_Name,
    Total_Revenue
FROM CustomerRevenue
ORDER BY Total_Revenue DESC;


/* 13. CATEGORY REVENUE USING CTE
    Business Question:
    Which categories contribute the most revenue?
*/

WITH CategoryRevenue AS
(
    SELECT
        p.Category,
        SUM(od.Quantity * p.Price * (1 - od.Discount)) AS Total_Revenue
    FROM Order_Details od
    INNER JOIN Products p
        ON od.Product_ID = p.Product_ID
    GROUP BY p.Category
)
SELECT *
FROM CategoryRevenue
ORDER BY Total_Revenue DESC;